name: Structure
api: [2.0.0, 3.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]
main: Structure\Structure
version: 1.0
authors: [GlowstoneMC, Muqsit]
website: https://github.com/GlowstoneMC/Glowstone
commands:
  structure:
    aliases: ["str"]
    permission: struct.ure
permissions:
  struct.ure:
    default: op